# SPDX-License-Identifier: GPL-2.0-only
TECHPACK?=y

obj-${TECHPACK} += audio/
obj-${TECHPACK} += camera/
obj-${TECHPACK} += display/
obj-${TECHPACK} += stub/
obj-${TECHPACK} += video/

header-${TECHPACK} += audio/include/uapi/
header-${TECHPACK} += camera/include/uapi/
header-${TECHPACK} += stub/include/uapi/
